In [4]:
import numpy as np
a=np.array(10)
b=np.array([10,11])
c=np.array([[10,11],[12,13]])
d=np.array([[[10,11],[12,13],[14,15]]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)


10
0
[10 11]
1
[[10 11]
 [12 13]]
2
[[[10 11]
  [12 13]
  [14 15]]]
3


In [6]:
#array indexing
arr1=np.array([1,2,3,4,5])
print(arr1[1]+arr1[2])

5


In [17]:
#slicing from 1 dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:4])

[1 2 3 4]


In [18]:
#negative slicing from 1 dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:
#slicing from 2 dimensional array
import numpy as np

arr = np.array([[1, 2, 3],[ 4, 5, 6]])

print(arr[0,1])

2


In [27]:
#slicing from 3 dimensional array
import numpy as np

arr = np.array([[[1,2,3] ,[4, 5,6] ,[7,8,9]]])

print(arr[0,1,2])

6
